//This file is auto generated by Tool/Auto Gen Code
using UnityEngine;
using UnityEngine.UI;
using TMPro;

	public class CharacterSelectView : UIBaseView
    {
		public TextMeshProUGUI TFName;
		public TextMeshProUGUI TFFitness;
		public TextMeshProUGUI TFProfile1;
		public TextMeshProUGUI TFProfile2;
		public TextMeshProUGUI TFProfile3;
		public TextMeshProUGUI TFProfile4;
		public TextMeshProUGUI TFScene;
		public TextMeshProUGUI TFStory;
		public TextMeshProUGUI TFCollect;
		public Button BtnEnter;
		public RectTransform Content;
		public GameObject CharacterItem;
		public TextMeshProUGUI TFDesc;
		public Image BG;
		protected override void OnInit(Transform holder)
		{
			var itemRef = holder.GetComponent<UIItemReference>();
			if(itemRef == null) return;
			var itemVarList = itemRef.itemVarList;
			if(itemVarList == null || itemVarList.Count == 0) return;
			TFName = itemVarList[0].Target.GetComponent<TextMeshProUGUI>();
			TFFitness = itemVarList[1].Target.GetComponent<TextMeshProUGUI>();
			TFProfile1 = itemVarList[2].Target.GetComponent<TextMeshProUGUI>();
			TFProfile2 = itemVarList[3].Target.GetComponent<TextMeshProUGUI>();
			TFProfile3 = itemVarList[4].Target.GetComponent<TextMeshProUGUI>();
			TFProfile4 = itemVarList[5].Target.GetComponent<TextMeshProUGUI>();
			TFScene = itemVarList[6].Target.GetComponent<TextMeshProUGUI>();
			TFStory = itemVarList[7].Target.GetComponent<TextMeshProUGUI>();
			TFCollect = itemVarList[8].Target.GetComponent<TextMeshProUGUI>();
			BtnEnter = itemVarList[9].Target.GetComponent<Button>();
			Content = itemVarList[10].Target.GetComponent<RectTransform>();
			CharacterItem = itemVarList[11].Target.gameObject;
			TFDesc = itemVarList[12].Target.GetComponent<TextMeshProUGUI>();
			BG = itemVarList[13].Target.GetComponent<Image>();
		}
	}