//This file is auto generated by Tool/Auto Gen Code
using UnityEngine;
using UnityEngine.UI;
using TMPro;

	public class LoginPanelView : UIBaseView
    {
		public TMP_InputField InputIP;
		public TMP_InputField InputName;
		public Button BtnLogin;
		protected override void OnInit(Transform holder)
		{
			var itemRef = holder.GetComponent<UIItemReference>();
			if(itemRef == null) return;
			var itemVarList = itemRef.itemVarList;
			if(itemVarList == null || itemVarList.Count == 0) return;
			InputIP = itemVarList[0].Target.GetComponent<TMP_InputField>();
			InputName = itemVarList[1].Target.GetComponent<TMP_InputField>();
			BtnLogin = itemVarList[2].Target.GetComponent<Button>();
		}
	}