//This file is auto generated by Tool/Auto Gen Code
using UnityEngine;
using UnityEngine.UI;
using TMPro;

	public class MainPanelView : UIBaseView
    {
		public Button BtnBack;
		public TMP_InputField Input;
		public Button BtnSend;
		public GameObject AskContent;
		public TextMeshProUGUI TFAsk;
		public TextMeshProUGUI TFCharacter;
		public GameObject AnswerContent;
		public TextMeshProUGUI TFAnswer;
		public GameObject ShortCut;
		public GameObject ShortCut1;
		public GameObject ShortCut2;
		public GameObject ShortCut3;
		public Button BtnMemory;
		public TextMeshProUGUI TFMemory;
		protected override void OnInit(Transform holder)
		{
			var itemRef = holder.GetComponent<UIItemReference>();
			if(itemRef == null) return;
			var itemVarList = itemRef.itemVarList;
			if(itemVarList == null || itemVarList.Count == 0) return;
			BtnBack = itemVarList[0].Target.GetComponent<Button>();
			Input = itemVarList[1].Target.GetComponent<TMP_InputField>();
			BtnSend = itemVarList[2].Target.GetComponent<Button>();
			AskContent = itemVarList[3].Target.gameObject;
			TFAsk = itemVarList[4].Target.GetComponent<TextMeshProUGUI>();
			TFCharacter = itemVarList[5].Target.GetComponent<TextMeshProUGUI>();
			AnswerContent = itemVarList[6].Target.gameObject;
			TFAnswer = itemVarList[7].Target.GetComponent<TextMeshProUGUI>();
			ShortCut = itemVarList[8].Target.gameObject;
			ShortCut1 = itemVarList[9].Target.gameObject;
			ShortCut2 = itemVarList[10].Target.gameObject;
			ShortCut3 = itemVarList[11].Target.gameObject;
			BtnMemory = itemVarList[12].Target.GetComponent<Button>();
			TFMemory = itemVarList[13].Target.GetComponent<TextMeshProUGUI>();
		}
	}