//This file is auto generated by Tool/Auto Gen Code
using UnityEngine;
using UnityEngine.UI;
using TMPro;

	public class PhotoPanelView : UIBaseView
    {
		public Button BtnBack;
		public GameObject ImgPreview;
		public RectTransform Content;
		public Image MaskImg;
		public Button BtnMask;
		protected override void OnInit(Transform holder)
		{
			var itemRef = holder.GetComponent<UIItemReference>();
			if(itemRef == null) return;
			var itemVarList = itemRef.itemVarList;
			if(itemVarList == null || itemVarList.Count == 0) return;
			BtnBack = itemVarList[0].Target.GetComponent<Button>();
			ImgPreview = itemVarList[1].Target.gameObject;
			Content = itemVarList[2].Target.GetComponent<RectTransform>();
			MaskImg = itemVarList[3].Target.GetComponent<Image>();
			BtnMask = itemVarList[4].Target.GetComponent<Button>();
		}
	}