//This file is auto generated by Tool/Auto Gen Code
using UnityEngine;
using UnityEngine.UI;
using TMPro;

	public class StoryPanelView : UIBaseView
    {
		public TextMeshProUGUI TFContent;
		public Button BtnNext;
		protected override void OnInit(Transform holder)
		{
			var itemRef = holder.GetComponent<UIItemReference>();
			if(itemRef == null) return;
			var itemVarList = itemRef.itemVarList;
			if(itemVarList == null || itemVarList.Count == 0) return;
			TFContent = itemVarList[0].Target.GetComponent<TextMeshProUGUI>();
			BtnNext = itemVarList[1].Target.GetComponent<Button>();
		}
	}